'use strict';

module.exports = {
  SET_APP_STATE: 'SET_APP_STATE',
  OFFLINE: -5,
  SOFFLINE: -2,
  SONLINE: 2,
  ONLINE: 5,

  NOT_FOUND: 'NOT_FOUND',

  FUNCTOR_HELPER: 'FUNCTOR_HELPER',
  ADD_PLUGIN: 'ADD_PLUGIN',
  REMOVE_PLUGIN: 'REMOVE_PLUGIN',
  ADD_FUNCTOR_HANDLE: 'ADD_REQUEST_HANDLE',
  INIT_FUNCTOR_HANDLE: 'INIT_REQUEST_HANDLE',
  DEFAULT_APP: 'DEFAULT_APP',
};
