'use strict';

module.exports = {
  SET_APP_STATE: 'SET_APP_STATE',
  OFFLINE: -5,
  SOFFLINE: -2,
  SONLINE: 2,
  ONLINE: 5,

  PLUGIN: 'PLUGIN',
  ADD_PLUGIN: 'ADD_PLUGIN',
  REMOVE_PLUGIN: 'REMOVE_PLUGIN',
  ADD_REQUEST_HANDLER: 'ADD_REQUEST_HANDLER',
  DEFAULT_APP: 'DEFAULT_APP',
};
